# Generated by Django 4.2.3 on 2024-03-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='honours1',
        ),
    ]
